version: "3"

services:
  infovis-neo4j:
    image: neo4j:5.25.1-community
    ports:
      - 7687:7687
      - 7474:7474
    environment:
      - NEO4J_AUTH=neo4j/infovis24
    volumes:
      - ./plugins:/plugins
