version: '3.8'

services:
  app:
    build: .
    ports:
      - "3500:3500"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./data:/usr/src/app/data
    environment:
      - NODE_ENV=development